// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AIChat(arg1:string,arg2:string):Promise<string>;

export function AISuggest(arg1:string,arg2:string):Promise<string>;

export function CountChars(arg1:string):Promise<number>;

export function CountWords(arg1:string):Promise<number>;

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetAppDir():Promise<string>;

export function GetConfig():Promise<main.AppConfig>;

export function GetConfigPath():Promise<string>;

export function GetDataDir():Promise<string>;

export function GetFileExtension(arg1:string):Promise<string>;

export function IsMarkdownFile(arg1:string):Promise<boolean>;

export function OpenFile(arg1:string):Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function ReadDirectory(arg1:string):Promise<Array<main.FileInfo>>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function StartFileWatcher(arg1:string):Promise<void>;

export function StopFileWatcher():Promise<void>;

export function UpdateAIConfig(arg1:main.AIConfig):Promise<void>;

export function UpdateLastDir(arg1:string):Promise<void>;
