// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIChat(arg1, arg2) {
  return window['go']['main']['App']['AIChat'](arg1, arg2);
}

export function AISuggest(arg1, arg2) {
  return window['go']['main']['App']['AISuggest'](arg1, arg2);
}

export function CountChars(arg1) {
  return window['go']['main']['App']['CountChars'](arg1);
}

export function CountWords(arg1) {
  return window['go']['main']['App']['CountWords'](arg1);
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetAppDir() {
  return window['go']['main']['App']['GetAppDir']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetFileExtension(arg1) {
  return window['go']['main']['App']['GetFileExtension'](arg1);
}

export function IsMarkdownFile(arg1) {
  return window['go']['main']['App']['IsMarkdownFile'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function ReadDirectory(arg1) {
  return window['go']['main']['App']['ReadDirectory'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function StartFileWatcher(arg1) {
  return window['go']['main']['App']['StartFileWatcher'](arg1);
}

export function StopFileWatcher() {
  return window['go']['main']['App']['StopFileWatcher']();
}

export function UpdateAIConfig(arg1) {
  return window['go']['main']['App']['UpdateAIConfig'](arg1);
}

export function UpdateLastDir(arg1) {
  return window['go']['main']['App']['UpdateLastDir'](arg1);
}
